service: mc-report-client-serverless
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'stg'}
  region: ${opt:region, 'us-west-2'}

functions:
  app:
    handler: app-serverless.handler
    timeout: 30
    events:
      - sns: arn:aws:sns:us-west-2:982834960524:mailchimp-reporting-api-import-result